### PR TITLE
feat: add nanopb support

### LINKED ISSUE #164: [Feature]: Add nanopb support
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Dynamic memory allocation is mandatory in **protobuf-c**, but it is a resource-consuming practice to use dynamic memory allocation in many embedded devices. Even some low-end chips do not support malloc operation, while **nanopb** can use static memory allocation to perform encoding and decoding operations, so we hope to add **nanopb** support.

### Acceptance Criteria

_No response_

### Suggestions for a technical implementation

https://github.com/nanopb/nanopb

### PR DESCRIPTION
**Pull request by strophy**
Resolves #164 

Add nanopb support

### CODE REVIEW

**Comment by strophy** [comment]
This currently fails with:
```
#0 1.036 [63] Error loading Python lib '/usr/bin/libpython3.11.so.1.0': dlopen: Error loading shared library /usr/bin/libpython3.11.so.1.0: No such file or directory
#0 1.036 --nanopb_out: protoc-gen-nanopb: Plugin failed with status code 255.
```

Is there any way to build this without 33MB of Python dependencies?

**Comment by strophy** [comment]
@rvolosatovs this increases the image size by 20MB after compression, but otherwise works fine.

**Review by rvolosatovs — APPROVED** [review]

**Comment by rvolosatovs** [comment]
Just a small question, do we need to do anything to make Renovate pick up updates for this one?

**Comment by strophy** [comment]
Yes, I forgot to do that for a couple of the recent additions so I will open a new PR now to update Renovate.

**Pull request merged**
