### PR TITLE
chore: update deps

### PR DESCRIPTION
**Pull request by strophy**
This PR updates many dependencies in `deps.list` and renames `github.com/envoyproxy/protoc-gen-validate` to its new home at `github.com/bufbuild/protoc-gen-validate` (note: github.com only, go package remains at `envoyproxy/protoc-gen-validate`.

### CODE REVIEW

**Review by rvolosatovs — APPROVED** [review]
Awesome, thanks for working on this!
I'll merge as soon as CI passes

**Comment by rvolosatovs** [comment]
Looks like CI is not too happy about https://github.com/rvolosatovs/docker-protobuf/pull/108/commits/c4ff7d958b4d944c039b2f30e4a32defb8dfa978, should we drop it and merge?

**Comment by strophy** [comment]
This works for me locally, what is the error in CI? I don't have permissions to view CI logs on this repo it seems.

But yes, totally go ahead and drop the broken commit and merge :) Would really appreciate a release and updated multiarch docker builds afterwards if there aren't too many more things waiting for v4.0.0?

**Comment by strophy** [comment]
Hi, I looked into reverting the change to the `NODE_VERSION` variable and found it is never actually consumed anywhere, in fact this is no longer required since #104 removed TypeScript and `protoc-gen-ts` [here](https://github.com/rvolosatovs/docker-protobuf/pull/104/commits/ae3ca41c6ee12e9610b72dddbe361dfc01ca5cb2#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L287). So since I still can't see CI results, I've pushed a commit to remove this from config entirely.

**Comment by rvolosatovs** [comment]
> Hi, I looked into reverting the change to the `NODE_VERSION` variable and found it is never actually consumed anywhere, in fact this is no longer required since #104 removed TypeScript and `protoc-gen-ts` [here](https://github.com/rvolosatovs/docker-protobuf/pull/104/commits/ae3ca41c6ee12e9610b72dddbe361dfc01ca5cb2#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L287). So since I still can't see CI results, I've pushed a commit to remove this from config entirely.

I don't know why this is the case, I can't see the logs myself either.

**Review by rvolosatovs — APPROVED** [review]

**Comment by rvolosatovs** [comment]
Well, yolo I guess :man_shrugging: 

Thanks for the PR!

**Pull request merged**
